config/routes.rb
Rails.application.routes.draw do

  #devise routes
  devise_for :users
  devise_for :admins
  devise_for :agents

  root 'dashboard#index'

  #restful CRUD controllers
  resources :events, only: [:index, :create, :new, :edit, :update]

  resources :app_users, only: [:index, :create, :new]

end

app/models/admin.rb
class Admin < User

end

app/models/agent.rb
class Agent < User

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	validates :name, presence: true
	validates :start_time, presence: true
	validates :end_time, presence: true
	validates :image, presence: true

  	belongs_to :planner, :class_name => 'User', :foreign_key => 'user_id'

  	has_one_attached :image, :dependent => :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events
  
end

app/controllers/ajax_controller.rb
class AjaxController < ActionController::Base
	add_flash_types :info, :error, :warning
	devise_group :user, contains: [:admin, :agent]
	skip_before_action :verify_authenticity_token  

	def after_sign_in_path_for(resource)
	  root_path 
	end


end

app/controllers/app_users_controller.rb
class AppUsersController < ApplicationController

	def index
		@users = User.all
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :info, :error, :warning
	devise_group :user, contains: [:admin, :agent]
	skip_before_action :verify_authenticity_token  

	def after_sign_in_path_for(resource)
	  root_path 
	end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

	def index
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController


	def index
		@q = Event.ransack(params[:q])
  		@events = @q.result.paginate(page: params[:page], per_page: 5)
	end

	def new
		@event = Event.new
	end

	def create
		planner = User.find_by(id: event_params[:planner].to_i)
		@event = Event.new(event_params.except(:planner, :image))
		@event.planner = planner
		@event.image.attach(io: event_params[:image].tempfile, filename: "xyz.pdf", content_type: "application/pdf")  if event_params[:image].present? 

		if @event.save
			flash[:notice] = "Event was saved"
		else
			flash[:error] = "Event was not saved. #{@event.errors.full_messages.to_sentence}"
		end
		redirect_to root_path
	end

	def edit
		@event = Event.find_by(id: params[:id])
	end

	def update
		planner = User.find_by(id: event_params[:planner].to_i)
		@event = Event.find_by(id: params[:id])
		@event.planner = planner
		@event.image.attach(io: event_params[:image].tempfile, filename: "xyz.pdf", content_type: "application/pdf")  if event_params[:image].present? 

		if @event.update(event_params.except(:planner))
			flash[:notice] = "Event was updated."
		else
			flash[:error] = "Event was not updated. #{@event.errors.full_messages.to_sentence}"
		end
		redirect_to root_path
	end


	private 
		def event_params
			params.require(:event).permit(:name, :planner, :star, :favorite, :image, :start_time, :end_time)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app_users/index.html.erb
<div class="row">
	<div class="col-lg-6 offset-lg-3">
		<div class="card">
		  <div class="card-header">
		  	<center><h4>List Users</h4></center>
		  </div>
		  <div class="card-body">
			<table class="table">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Name</th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% @users.each_with_index do |user, i| %>
			    <tr>
			      <th scope="row"><%= i+1 %></th>
			      <td><%= user.email %></td>
			    </tr>
			    <% end %>
			  </tbody>
			</table>

		  </div>
		</div>
	</div>
</div>

app/views/app_users/new.html.erb
<div class="row">
	<div class="col-lg-6 offset-md-3">
		<div class="card">
		  <div class="card-header">
		  	<center><h4>Create User</h4></center>
		  </div>
		  <div class="card-body">
			<%= simple_form_for(@agent, url: app_users_path, method: :post) do |f| %>
				<div class="row">
					<div class="col-lg-12">
						<%= f.input :email, input_html: { class: 'form-control ' } %>
						<%= f.input :password, input_html: { class: 'form-control ' } %>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-lg-12">
						<center>
							<%= f.button :submit,  class: "btn btn-primary" %>
						</center>
					</div>
				</div>
			<% end %>
		  </div>
		</div>
	</div>
</div>

app/views/dashboard/index.html.erb
<p> This is your dasboard </p>

app/views/events/edit.html.erb
<div class="row">
	<div class="col-lg-6 offset-md-3">
		<div class="card">
		  <div class="card-header">
		  	<center><h4>Create Event</h4></center>
		  </div>
		  <div class="card-body">
			<%= simple_form_for(@event, url: event_path, method: :patch) do |f| %>
				<div class="row">
					<div class="col-lg-12">
						<%= f.input :name, input_html: { class: 'form-control ' } %>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-lg-6">
						<%= f.label :planner, 'Planner' %> <br>

  						<%= f.collection_select :planner, User.all, :id, :email, include_blank: true, selected: @event.planner.id %>
					</div>
					<div class="col-lg-1 offset-sm-1">
						<%= f.label :star, 'Star' %> <br>
  						<%= f.check_box :star  %>
					</div>					
					<div class="col-lg-1 offset-sm-1">
						<%= f.label :favorite, 'Favorite' %> <br>
  						<%= f.check_box :favorite  %>
					</div>
				</div>
				<br>	
				<div class="row">
					<div class="col-lg-12">
						<%= f.label :start_time, 'Start Time' %> <br>
   						 <%= f.datetime_select :start_time %>
					</div>
				</div>				
				<br>	
				<div class="row">
					<div class="col-lg-12">
						<%= f.label :end_time, 'End Time' %> <br>
   						 <%= f.datetime_select :end_time %>
					</div>
				</div>
				<br>			
				<div class="row">
					<div class="col-lg-12">
						<%= f.file_field :image %>
						<br>
						<br>
						<%= image_tag @event.image, style: "width: 200px" %>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-lg-12">
						<center>
							<%= f.button :submit,  class: "btn btn-primary" %>
						</center>
					</div>
				</div>
			<% end %>
		  </div>
		</div>
	</div>
</div>

app/views/events/index.html.erb
<div class="row">
	<div class="col-lg-8 offset-lg-3">
		<div class="card">
		  <div class="card-header">
		  	<center><h4>List Events</h4></center>
		  </div>
		  <div class="card-body">
		  	<div class="row">
			<%= search_form_for @q do |f| %>
				<div class="col-lg-2">
			  		<%= f.label :name_cont, "Name" %>
			  		<%= f.search_field :name_cont, class: 'form-control ' %>
			  	</div>
			  	<br>
			  	<div class="col-lg-2">
			  		<%= f.submit class: 'btn btn-primary' %>
				</div>
			<% end %>
			</div>
		  </div>
		</div>
	</div>
</div>
<br>

<br>
<div class="row">
	<div class="col-lg-8 offset-lg-3">
		<div class="card">
		  <div class="card-header">
		  	<center><h4>List Events</h4></center>
		  </div>
		  <div class="card-body">
			<table class="table">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col"><%= sort_link(@q, :name) %></th>
			      <th scope="col">Planner</th>
			      <th scope="col"><%= sort_link(@q, :start_time) %></th>
			      <th scope="col"><%= sort_link(@q, :favorite) %></th>
			      <th scope="col"></th>
			    </tr>
			  </thead>
			  <tbody>
			  	<% @events.each_with_index do |event, i| %>
				    <tr>
				      <th scope="row"><%= i+1 %></th>
				      <td><%= event.name %></td>
				      <td><%= event.planner.email %></td>
				      <td><%= event.start_time.strftime('%Y-%m-%d %I:%M:%S') %></td>
					  <td><%= event.favorite %></td>
				      <td>
	        			<%= link_to "Edit", edit_event_path(event), class: "nav-link"%>
				      </td>
				    </tr>
			    <% end %>
				<%= will_paginate @events  %>
			  </tbody>
			</table>
		  </div>
		</div>
	</div>
</div>
<br>
<br>

app/views/events/new.html.erb
<div class="row">
	<div class="col-lg-6 offset-md-3">
		<div class="card">
		  <div class="card-header">
		  	<center><h4>Create Event</h4></center>
		  </div>
		  <div class="card-body">
			<%= simple_form_for(@event, url: events_path) do |f| %>
				<div class="row">
					<div class="col-lg-12">
						<%= f.input :name, input_html: { class: 'form-control ' } %>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-lg-6">
						<%= f.label :planner, 'Gender' %> <br>

  						<%= f.collection_select :planner, User.all, :id, :email, include_blank: true %>
					</div>
					<div class="col-lg-1 offset-sm-1">
						<%= f.label :star, 'Star' %> <br>
  						<%= f.check_box :star  %>
					</div>					
					<div class="col-lg-1 offset-sm-1">
						<%= f.label :favorite, 'Favorite' %> <br>
  						<%= f.check_box :favorite  %>
					</div>
				</div>
				<br>	
				<div class="row">
					<div class="col-lg-12">
						<%= f.label :start_time, 'Start Time' %> <br>
   						 <%= f.datetime_select :start_time %>
					</div>
				</div>				
				<br>	
				<div class="row">
					<div class="col-lg-12">
						<%= f.label :end_time, 'End Time' %> <br>
   						 <%= f.datetime_select :end_time %>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-lg-6">
						<%= f.label :image, 'Image' %> <br>

  						<%= f.file_field :image %>
					</div>
				</div>
				<br>
				<div class="row">
					<div class="col-lg-12">
						<center>
							<%= f.button :submit,  class: "btn btn-primary" %>
						</center>
					</div>
				</div>
			<% end %>
		  </div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsEventApp2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
    <%= render "shared/navbar" %>
    <% end %>
    <div class="container pt-5">
      <% if flash.notice %>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "alert alert-info" %>
        <% end %>
      <% else %>
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "alert alert-danger" %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">

  <div class="container-fluid">
    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="navbar-brand" href="#">Event App</a>
      </li>
      <li class="nav-item">
        <%= link_to "Create Event", new_event_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "List Events", events_path, class: "nav-link"%>

      </li>
      <li class="nav-item">
        <%= link_to "List Users", app_users_path, class: "nav-link"%>
      </li>
    </ul>
      <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Sign Out",  destroy_user_session_path, :method => :delete , class: "nav-link"%>
      </li>

  </ul>
  </div>

</nav>